---
# Variable setup.
- debug:
    msg: "{{ redis_master_ip }} : {{ redis_port }}"
  tags: facts
  ignore_errors: true
  # when: inventory_host_name in groups['redis_master']
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- debug:
    msg: "{{redis_conf_path}}"
- name: Ensure Redis configuration dir exists.
  become: yes
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755
  
- name: Ensure Redis is configured.
  become: yes
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis

# 增加哨兵模式
- name: Ensure Sentinel is configured.
  become: yes
  template:
    src: sentinel.conf.j2
    dest: "{{ redis_sentinel_path }}"
    mode: "{{ redis_sentinel_mode }}"
  when: redis_sentinel 
  notify: restart redis-sentinel

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Ensure Redis is running and enabled on boot.
  become: true
  service: "name={{ redis_daemon }} state=started enabled=yes"

- name: Ensure Redis-sentinel is running and enabled on boot.
  become: true
  service: 
    name: redis-sentinel
    state: started 
    enabled: yes
  when: redis_sentinel  