---
# - name: Ensure Redis is installed.
#   become: yes
#   package:
#     name: "{{ redis_package }}"
#     state: present
#     enablerepo: "{{ redis_enablerepo | default(omit, true) }}"
- name: Ensure Redis is installed for python2.
  become: true
  yum:
    name:
      - "{{ item}}"
    state: present
  with_items: "{{ redis_package }}"

# 开启防火墙6379端口
- name: open redis port
  become: true
  firewalld:
    port:  "{{redis_port}}/tcp"
    zone: public
    permanent: yes
    state: enabled
    immediate: true